[package]
name = "inth-oauth2"
version = "0.11.0"

description = "OAuth2 client"
keywords = ["authentication", "authorization", "auth", "oauth"]

authors = ["Curtis McEnroe <programble@gmail.com>"]
license = "ISC"

repository = "https://github.com/programble/inth-oauth2"
readme = "README.md"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures = "0.1"
hyper = "0.11"
hyper-rustls = "0.9"
serde = "1"
serde_derive = "1"
serde_json = "1"
url = "1.5"

[dev-dependencies]
yup-hyper-mock = "2.0"
